const env = require('dotenv');
env.config();
require('reflect-metadata');
require('./database');
const express = require ('express');
const routes = require ('./routes/routesOne');
const routeLoja = require ('./routes/routes_Loja');
const routeUsuario = require ('./routes/routes_Usuario');
const routeLojaEndereco = require ('./routes/routes_LojaEndereco');
const routeDadosBancarios = require('./routes/routes_DadosBancarios');
const routeUsuarioEndereco = require('./routes/routes_UsuarioEndereco');
const routeUsuarioLoja = require('./routes/routes_UsuarioLoja');
const port = 3000;
const app = express ();
app.use(express.json());

console.log(process.env.TESTE);
app.use(routes);
app.use(routeLoja);
app.use(routeUsuario);
app.use(routeLojaEndereco);
app.use(routeDadosBancarios);
app.use(routeUsuarioEndereco);
app.use(routeUsuarioLoja);
app.listen(port);